"use client";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { useEditorStore } from "@/store/editorStore";
import { Mermaid } from "./Mermaid";
import { Badge } from "../ui/badge";
import { Separator } from "../ui/separator";

interface MindMapModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function MindMapModal({ open, onOpenChange }: MindMapModalProps) {
  const { mindmap, summary, tags } = useEditorStore();

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl h-auto max-h-[80vh]">
        <DialogHeader>
          <DialogTitle>AI Generated Content</DialogTitle>
          <DialogDescription>
            Here is the Mind Map and other content generated by the AI based on your document.
          </DialogDescription>
        </DialogHeader>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 py-4 overflow-y-auto">
            <div className="md:col-span-2">
                <h3 className="text-lg font-semibold mb-2">Mind Map</h3>
                <div className="rounded-lg border bg-card text-card-foreground shadow-sm p-4 min-h-[300px]">
                    {mindmap ? <Mermaid chart={mindmap} /> : <p className="text-muted-foreground">No mind map generated.</p>}
                </div>
            </div>
            <div className="space-y-6">
                <div>
                    <h3 className="text-lg font-semibold mb-2">Summary</h3>
                    <div className="text-sm p-4 rounded-lg bg-secondary text-secondary-foreground">
                        {summary || <span className="text-muted-foreground">No summary generated.</span>}
                    </div>
                </div>
                <div>
                    <h3 className="text-lg font-semibold mb-2">Tags</h3>
                    <div className="flex flex-wrap gap-2">
                        {tags.length > 0 ? tags.map((tag, index) => (
                            <Badge key={index} variant="secondary">{tag}</Badge>
                        )) : <p className="text-sm text-muted-foreground">No tags generated.</p>}
                    </div>
                </div>
            </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
